### PR TITLE
Return nil when xml-rpc returns an empty array.

### PR DESCRIPTION
**Pull request by minsikl**
SoftLayer_Network_Storage::removeAccessFromHost or removeAccessFromHost return SoftLayer_Network_Storage_Allowed_Host. However, when the return value is empty and xml-rpc is used, SL API returns empty array `<array> </data></array>` not empty struct and it causes unmarshal errors. 

The following logic returns nil when `val` is not an array but the XML entry is an empty array. This PR is related to the issue https://github.com/softlayer/terraform-provider-softlayer/issues/132

### CODE REVIEW

**Comment by renier** [comment]
@minsikl What is the complete XML response from SoftLayer? and what is the SL data structure being used on the client side to decode the XML? Also, what is the name of the mismatching field in that struct?

**Comment by minsikl** [comment]
@renier Here is an example:
```
Request:
POST /xmlrpc/v3/SoftLayer_Network_Storage HTTP/1.1
<?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>removeAccessFromHostList</methodName><params><param><value><struct><member><name>headers</name><value><struct><member><name>authenticate</name><value><struct><member><name>username</name><value><string>abc</string></value></member><member><name>apiKey</name><value><string>abc</string></value></member></struct></value></member><member><name>SoftLayer_Network_StorageInitParameters</name><value><struct><member><name>id</name><value><int>22303335</int></value></member></struct></value></member></struct></value></member></struct></value></param><param><value><array><data><value><struct><member><name>id</name><value><int>73259895</int></value></member><member><name>objectType</name><value><string>SoftLayer_Network_Subnet_IpAddress</string></value></member></struct></value></data></array></value></param></params></methodCall>

Response:
<?xml version="1.0" encoding="utf-8"?>
<params>
 <param>
  <value>
   <array>
    <data>
     <value>
      <array>
       <data/>
      </array>
     </value>
    </data>
   </array>
  </value>
 </param>
</params>
```

**Comment by renier** [comment]
@minsikl Was this the error you were getting? `error: type mismatch - can't unmarshal struct to slice`

**Comment by minsikl** [comment]
@renier Yes.

**Comment by renier** [comment]
When getting any other array response, the organization is different:
```
<?xml version="1.0" encoding="utf-8"?>
<params>
<param>
 <value>
  <array>
   <data>
    <value>
     <struct>
      <member>
       <name>domain</name>
       <value>
        <string>ms.com</string>
       </value>
      </member>
      <member>
       <name>hostname</name>
       <value>
        <string>stgtest</string>
       </value>
      </member>
     </struct>
    </value>
    <value>
     <struct>
      <member>
       <name>domain</name>
       <value>
        <string>ms.com</string>
       </value>
      </member>
      <member>
       <name>hostname</name>
       <value>
        <string>storagetest</string>
       </value>
      </member>
     </struct>
    </value>
   </data>
  </array>
 </value>
</param>
</params>
```
There is no second-level nested array as in the other example above. This makes it a bug in SLAPI XMLRPC, as for empty array responses it adds an empty array as a first element of a first-level array (i.e. [][]struct instead of []struct).

By the time the error happens, the code has already walked the response value down to the first element type of the provided slice, and the incoming data still has a second-level array to decode which causes the mismatch.

I'm trying to see if there is a more subtle way to work around this.

**Comment by renier** [comment]
@minsikl Check the branch `unexpected-array-embeds`. It seems to work for me.  You can use the following to test:

```go
package main

import (
	"fmt"

	"github.com/renier/xmlrpc"
	"github.com/softlayer/softlayer-go/datatypes"
)

const input = `<?xml version="1.0" encoding="utf-8"?>
<params>
 <param>
  <value>
   <array>
    <data>
     <value>
      <array>
       <data/>
      </array>
     </value>
    </data>
   </array>
  </value>
 </param>
</params>`

func main() {
	var allowedHosts []datatypes.Network_Storage_Allowed_Host

	response := xmlrpc.NewResponse([]byte(input), 200)
	err := response.Unmarshal(&allowedHosts)
	if err != nil {
		fmt.Println(err.Error())
	}

	fmt.Println(len(allowedHosts), allowedHosts)
}

```

**Comment by minsikl** [comment]
@renier I checked `unexpected-array-embeds` branch and acceptance test for softlayer storage in terraform-softlayer provider worked.

**Pull request closed without merging**
